### ISSUE TITLE
Issue while testing MonetDBe-Java examples

### ISSUE THREAD

**Issue by Guillaume789** [MonetDBSolutions/MonetDBe-Java#2]
Hi,

I have installed the project and was testing the provided examples.
When I start the first HelloWorld example, I get an Exception:

Loading: iconv-2.dll
java.io.IOException: Library iconv-2.dll could not be found.
	at org.monetdb.monetdbe.MonetNative.loadLib(MonetNative.java:120)
	at org.monetdb.monetdbe.MonetNative.<clinit>(MonetNative.java:56)
	at org.monetdb.monetdbe.MonetConnection.<init>(MonetConnection.java:82)
	at org.monetdb.monetdbe.MonetDriver.connectJDBC(MonetDriver.java:107)
	at org.monetdb.monetdbe.MonetDriver.connect(MonetDriver.java:177)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at HelloWorld.main(HelloWorld.java:10)
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.monetdb.monetdbe.MonetNative.monetdbe_open(Ljava/lang/String;Lorg/monetdb/monetdbe/MonetConnection;IIII)Ljava/lang/String;
	at org.monetdb.monetdbe.MonetNative.monetdbe_open(Native Method)
	at org.monetdb.monetdbe.MonetConnection.<init>(MonetConnection.java:82)
	at org.monetdb.monetdbe.MonetDriver.connectJDBC(MonetDriver.java:107)
	at org.monetdb.monetdbe.MonetDriver.connect(MonetDriver.java:177)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at HelloWorld.main(HelloWorld.java:10)

The file monetdbe-java-1.0.jar (33Mo) is in the classpath !

Any idea what could be the problem ?

Thanks,
Guillaume

**My computer:**
OS Name	Microsoft Windows 10 Pro
Version	10.0.19042 Build 19042
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-K6TP1SK
System Manufacturer	Dell Inc.
System Model	XPS 13 7390
System Type	x64-based PC
System SKU	0962
Processor	Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz, 2304 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Dell Inc. 1.7.0, 22/10/2020
SMBIOS Version	3.2
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Dell Inc.
BaseBoard Product	0G2D0W
BaseBoard Version	A00
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.19041.906"
User Name	DESKTOP-K6TP1SK\guill
Time Zone	Romance Daylight Time
Installed Physical Memory (RAM)	16,0 GB
Total Physical Memory	15,8 GB
Available Physical Memory	4,71 GB
Total Virtual Memory	53,8 GB
Available Virtual Memory	34,7 GB
Page File Space	38,0 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	On
Virtualization-based security	Not enabled
Device Encryption Support	Elevation Required to View
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

**Comment by bernardom29** [comment]
How did you install the project? The windows version currently doesn't support manual building (it does, but not in a nice way at all).
So right now, you can both set it as a dependency in your maven project or download the jar and use it directly.

To set as a dependency (need to use the snapshot repo):
```
<repositories>
    <repository>
        <id>Sonatype Snapshot</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>

<dependency>
  <groupId>monetdb</groupId>
  <artifactId>monetdbe-java</artifactId>
  <version>1.0-SNAPSHOT</version>
  <classifier>windows</classifier>
</dependency>
```

Or if you want to download the jar, here's the latest windows snapshot:
[Download latest snapshot](https://oss.sonatype.org/service/local/repositories/snapshots/content/monetdb/monetdbe-java/1.0-SNAPSHOT/monetdbe-java-1.0-20210503.132004-3-windows.jar)

**Comment by Guillaume789** [comment]
Perfect, thank you.
Downloading the jar from this repository solved my problem.
