### ISSUE TITLE
What is the roadmap for Multithreaded access to connections and connection pooling

### ISSUE THREAD

**Issue by Guillaume789** [MonetDBSolutions/MonetDBe-Java#8]
Hi Bernardo,

could you please let me know is the roadmap for Multithreaded access to connections and connection pooling ?
I do really like the performance of MonetDB, however since the project has moved to MonetDBe, I cannot use it as these features are not an option for me (Multithreaded access and connection pooling).

Thanks,
Guillaume

**Comment by bernardom29** [comment]
Hi Guillaume,
Thanks for your continued interest in MonetDBe-Java!

We're releasing support for multi-threaded access to Connections on the next official MonetDBe-Java release, which should be out in the next few weeks. If you want this feature earlier, I can upload a development version with this fix. Are you using maven to get the driver?

Connection pooling is not a feature we support yet and it isn't on the development roadmap for now. However, I'll update this with a more concrete answer (if and when we'll add this feature), once the new release is out.

Thanks,
Bernardo

**Comment by Guillaume789** [comment]
Hi Bernardo,

Happy new year 2022 :)

Yes, I am using maven to get the library but if you can provide me a development version before I can take it in any form (manually download jar or maven).

Thanks,
Guillaume

**Comment by bernardom29** [comment]
Happy new year :)

You're using Windows, right? Here's the latest SNAPSHOT for windows.
Maven:
```
<dependency>
  <groupId>monetdb</groupId>
  <artifactId>monetdbe-java</artifactId>
  <version>1.11-SNAPSHOT</version>
  <classifier>windows</classifier>
</dependency>
```
Manual download:
https://oss.sonatype.org/service/local/repositories/snapshots/content/monetdb/monetdbe-java/1.11-SNAPSHOT/monetdbe-java-1.11-20220110.151548-17-windows.jar

Let us know if this solves your problem with multi-threaded access.

**Comment by Guillaume789** [comment]
Hi Bernardo,

many thanks for this snapshot release.
I am able to successfully run some queries in Swing GUI without issues.

However, I tried to open 2 applications in parallel and get below error (2 app using 1 DB connection each):

java.nio.file.AccessDeniedException: C:\Users\guill\AppData\Local\Temp\iconv-2.dll
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1185)
	at java.base/java.nio.file.Files.copy(Files.java:3132)
	at org.monetdb.monetdbe.MonetNative.loadLib(MonetNative.java:171)
	at org.monetdb.monetdbe.MonetNative.<clinit>(MonetNative.java:59)
	at org.monetdb.monetdbe.MonetConnection.connectNative(MonetConnection.java:133)
	at org.monetdb.monetdbe.MonetConnection.<init>(MonetConnection.java:79)
	at org.monetdb.monetdbe.MonetDriver.connectJDBC(MonetDriver.java:115)
	at org.monetdb.monetdbe.MonetDriver.connect(MonetDriver.java:184)
	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:52)
	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:374)
	at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:106)
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:649)
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:531)
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:731)
...

Exception in thread "Thread-2" java.lang.UnsatisfiedLinkError: 'java.lang.String org.monetdb.monetdbe.MonetNative.monetdbe_open(java.lang.String, org.monetdb.monetdbe.MonetConnection, int, int, int, int, java.lang.String)'
	at org.monetdb.monetdbe.MonetNative.monetdbe_open(Native Method)
	at org.monetdb.monetdbe.MonetConnection.connectNative(MonetConnection.java:133)
	at org.monetdb.monetdbe.MonetConnection.<init>(MonetConnection.java:79)
	at org.monetdb.monetdbe.MonetDriver.connectJDBC(MonetDriver.java:115)
	at org.monetdb.monetdbe.MonetDriver.connect(MonetDriver.java:184)
	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:52)
	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:374)
	at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:106)
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:649)
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:531)
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:731)
...

I think it is because the lib "iconv-2.dll" was already exploded in the temp folder and was used/locked by the first GUI instance. So the second app fails to explode the DLL at the same location (C:\Users\guill\AppData\Local\Temp\iconv-2.dll).

It should be possible to compare the libs checksum to see if the libs must be updated or not.
If the checksum match, then no need to deploy the DLL, otherwise delete old libs and copy new libs.

Thanks & regards,
Guillaume

**Comment by bernardom29** [comment]
Hi Guillaume,

Could you try this again with the newest version?
Just use the same maven dependency (it should download the latest snapshot) or use this direct download:
https://oss.sonatype.org/service/local/repositories/snapshots/content/monetdb/monetdbe-java/1.11-SNAPSHOT/monetdbe-java-1.11-20220111.174510-19-windows.jar

Thanks!

**Comment by Guillaume789** [comment]
Hi Bernardo,

I have just tested the new library.

At first I got below exception:

File already exists, no copy
File already exists, no copy
File already exists, no copy
File already exists, no copy
File already exists, no copy
File already exists, no copy
File already exists, no copy
File already exists, no copy
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\guill\AppData\Local\Temp\stream.dll: %1 is not a valid Win32 application
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383)
	at java.base/java.lang.Runtime.load0(Runtime.java:746)
	at java.base/java.lang.System.load(System.java:1857)
	at org.monetdb.monetdbe.MonetNative.loadLib(MonetNative.java:181)
	at org.monetdb.monetdbe.MonetNative.<clinit>(MonetNative.java:72)
	at org.monetdb.monetdbe.MonetConnection.connectNative(MonetConnection.java:133)
	at org.monetdb.monetdbe.MonetConnection.<init>(MonetConnection.java:79)
	at org.monetdb.monetdbe.MonetDriver.connectJDBC(MonetDriver.java:115)
	at org.monetdb.monetdbe.MonetDriver.connect(MonetDriver.java:184)
	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:52)
	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:374)
	at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:106)
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:649)
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:531)
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:731)
	at test.Test4.execute(Test4.java:165)
	at test.Test4.runQueries(Test4.java:87)
	at test.Test4.main(Test4.java:34)

Then I noticed that the file 'C:\Users\guill\AppData\Local\Temp\stream.dll' was 0, so I deleted all DLL libs in the temp folder and tested again.

After manually deleting the DLL, it is now working fine: I can run many test application in parallel (no conflict with temp DLL)
I will do more tests later.

Thanks,
Guillaume
